# Generated by Django 5.2.7 on 2025-11-03 17:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=50, unique=True, verbose_name='Número do contrato')),
                ('nome_empresa', models.CharField(max_length=100, verbose_name='Nome da Empresa')),
                ('objeto', models.TextField(verbose_name='Objeto do Contrato')),
                ('sei', models.CharField(max_length=50, verbose_name='SEI')),
                ('gestor_contrato', models.CharField(max_length=100, verbose_name='Gestor do Contrato')),
                ('fiscal_contrato', models.CharField(max_length=100, verbose_name='Fiscal do Contrato')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_termino', models.DateField(verbose_name='Data de Término')),
                ('vigencia', models.IntegerField(verbose_name='Vigência (meses)')),
                ('saldo_total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator('0')], verbose_name='Saldo Total')),
                ('secundario', models.BooleanField(default=False, help_text='Marque se o contrato é parte de um maior', verbose_name='Contrato secundário')),
                ('maior', models.CharField(blank=True, null=True, verbose_name='Contrato maior')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('concluído', 'Concluído'), ('cancelado', 'Cancelado')], default='ativo', max_length=20, verbose_name='Status do Contrato')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-nome_empresa'],
            },
        ),
        migrations.CreateModel(
            name='Saldo_mensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Nome')),
                ('ano', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2099)], verbose_name='Ano')),
                ('valor_gasto', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Gasto no Mês')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_mensais', to='contract.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Saldo Mensal',
                'verbose_name_plural': 'Saldos Mensais',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('contrato', 'mes', 'ano')},
            },
        ),
    ]
