# Generated by Django 5.2.7 on 2025-12-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_alter_contrato_saldo_total_alter_saldo_mensal_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('concluído', 'Concluído'), ('cancelado', 'Cancelado'), ('secundário', 'Secundário')], default='ativo', max_length=20, verbose_name='Status do Contrato'),
        ),
    ]
