# Generated by Django 5.2.7 on 2026-01-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_alter_contrato_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='email',
            field=models.BooleanField(default=False, verbose_name='Notificado'),
        ),
    ]
