# Generated by Django 5.2.7 on 2025-11-06 14:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria de Empenho',
                'verbose_name_plural': 'Categorias de Empenho',
            },
        ),
        migrations.CreateModel(
            name='ExercicioAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(unique=True, verbose_name='Ano do Exercício')),
                ('valor_orcamento', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor do Orçamento Anual')),
            ],
            options={
                'verbose_name': 'Exercício Anual',
                'verbose_name_plural': 'Exercícios Anuais',
            },
        ),
        migrations.CreateModel(
            name='CategoriaExercicioOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_orcamento_categoria', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Orçamento da Categoria')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.categoria')),
                ('exercicio_anual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.exercicioanual')),
            ],
            options={
                'verbose_name': 'Exercício Anual',
                'verbose_name_plural': 'Exercícios Anuais',
            },
        ),
        migrations.CreateModel(
            name='Empenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_empenho', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número do Empenho')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor do Empenho')),
                ('data_empenho', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Empenho')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('codigo_orcamentario', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código Orçamentário')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.categoria', verbose_name='Categoria')),
                ('exercicio_anual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.exercicioanual', verbose_name='Exercício Anual')),
            ],
            options={
                'verbose_name': 'Empenho',
                'verbose_name_plural': 'Empenhos',
                'unique_together': {('numero_empenho', 'exercicio_anual')},
            },
        ),
    ]
