# Generated by Django 5.2.7 on 2025-12-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaexercicioorcamento',
            options={'verbose_name': 'Orçamento por Categoria/Ano', 'verbose_name_plural': 'Orçamentos por Categoria/Ano'},
        ),
        migrations.AlterField(
            model_name='exercicioanual',
            name='valor_orcamento',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor do Orçamento Anual (Referência)'),
        ),
        migrations.AlterUniqueTogether(
            name='categoriaexercicioorcamento',
            unique_together={('exercicio_anual', 'categoria')},
        ),
    ]
